### ISSUE TITLE
[BUG] Caesar Cipher couldn't decrypt

### ISSUE THREAD

**Issue by dubeyanant** [inclinedadarsh/ciphered#3]
**Describe the bug**
doesn't work.

**To Reproduce**
Algo: Caesar Cipher
Key: 32
Plain text: Hellow
Ciphered text: Nkrruc
Returned decrypted text: Hello]

**Comment by inclinedadarsh** [comment]
Thanks @dubeyanant for finding the bug.

Would you like to work on this?

**Comment by dubeyanant** [comment]
Sure!

**Comment by inclinedadarsh** [comment]
That's great!
The issue is in this file: https://github.com/inclinedadarsh/ciphered/blob/main/src/lib/algorithms/caesar-cipher.ts
Specifically in the decrypt method.

Have a look at it and let me know if you need any other help.
I'm assigning this to you.

**Comment by inclinedadarsh** [comment]
Thanks a lot for the contribution @dubeyanant
