### ISSUE TITLE
[FEATURE] Add copy text button for both text area

### ISSUE THREAD

**Issue by inclinedadarsh** [inclinedadarsh/ciphered#7]
**Describe the solution you'd like**
Add a copy text button (in the red box given in the image below) so the users can easily copy plain/cipher text.

![image](https://github.com/inclinedadarsh/ciphered/assets/84132532/1adc02f4-d728-495d-8ae4-b88f90f844f1)

You can take reference from this StackOverflow question: https://stackoverflow.com/questions/39501289/in-reactjs-how-to-copy-text-to-clipboard

**Comment by dubeyanant** [comment]
Can I work on this?
